version: '3.5'

services:
  formacion-db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "xxxxxxxx"
      POSTGRES_DB: "adevintaff5"
